line-length = 120
target-version = "py311"

[lint]
select = [
  "E",   # Ошибки стиля из pycodestyle (PEP8)
  "F",   # Диагностика от Pyflakes (неиспользуемые/неопределённые переменные и т.п.)
  "B",   # flake8-bugbear (подозрительные конструкции и лучшие практики)
  "I",   # Сортировка импортов (isort-профиль Ruff)
  "UP",  # pyupgrade (советы по современному синтаксису Python)
  "ANN", # Аннотации типов (flake8-annotations)
  "D",   # Докстринги (pydocstyle)
]
ignore = [
  "D100", # Отсутствует докстринг в публичном модуле
  "D101", # Отсутствует докстринг в публичном классе
  "D104", # Отсутствует докстринг в публичном пакете
  "D105", # Отсутствует докстринг у магического метода
  "D107", # Отсутствует докстринг у __init__
  "D203", # Пустая строка перед докстрингом класса
  "D213", # Многострочный комментарий должен начинаться со второй строки (работает D212)
]

[lint.isort]
combine-as-imports = true
force-sort-within-sections = true
split-on-trailing-comma = true

[lint.pydocstyle]
convention = "pep257" # Стиль кода reST

[lint.flake8-annotations]
mypy-init-return = true

[lint.per-file-ignores]
# В тестах не обязательно писать возвращаемый тип
# Тесты не обязательно документировать
"**/test_*.py" = ["ANN201", "ANN202", "D"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"
docstring-code-format = true 